/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/webhooks/clerk'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/webhooks/clerk'
  id: '__root__' | '/' | '/api/webhooks/clerk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
